name: Build CPython for iOS

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.14.7
      - run: python3 build.py
      - uses: actions/upload-artifact@v7
        with:
          path: dist/python3-ios-rootful_3.14.7_iphoneos-arm.deb
          archive: false
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          path: dist/python3-ios-rootless_3.14.7_iphoneos-arm64.deb
          archive: false
          if-no-files-found: error
